// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUMxAQ8mGoWGFmxmSM5CaCqnTbPkxa3x4',
    appId: '1:729373058578:web:b91e6383417314a9099acb',
    messagingSenderId: '729373058578',
    projectId: 'kfriends-e88f8',
    authDomain: 'kfriends-e88f8.firebaseapp.com',
    storageBucket: 'kfriends-e88f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEAHhozY792PgstN46UtvNaWvffk150j0',
    appId: '1:729373058578:android:88e10c92526cf5ab099acb',
    messagingSenderId: '729373058578',
    projectId: 'kfriends-e88f8',
    storageBucket: 'kfriends-e88f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNc6EocNjb1gLWIgAEV59t5u3rZo8q21g',
    appId: '1:729373058578:ios:1279cccfd481f9a5099acb',
    messagingSenderId: '729373058578',
    projectId: 'kfriends-e88f8',
    storageBucket: 'kfriends-e88f8.appspot.com',
    iosBundleId: 'com.kfriends.app.kfriends',
  );
}
